name: Custome Analytics Code Deployment 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
  
      

    # ✅ Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # ✅ Install dependencies
    - name: Install dependencies\
      run: pip install -r requirements.txt
    
    - name: Install package
      run: pip install -e .

    # ✅ Run tests (CI part)
    - name: Run tests
      run: pytest tests/

    - name: Install dependencies
      run: pip install wheel setuptools

    - name:  create wheel file 
      run: python setup.py bdist_wheel

    - name: Get wheel filename
      run: |
        WHEEL_FILE=$(ls dist/*.whl | head -n 1)
        echo "WHEEL_FILE=$WHEEL_FILE" >> $GITHUB_ENV

    - name: copy wheel file 
      run: aws s3 cp "$WHEEL_FILE" s3://may-mani-2025-training-bucket/code/customer_analytics/

    - name: copy template file 

      run: aws s3 cp glue_upload_script s3://may-mani-2025-training-bucket/code/customer_analytics/ --recursive
